### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by vuxor** [nlukic97/zadatak_1#2]
https://github.com/nlukic97/zadatak_1/blob/0d5a2667b45129cb683cd0f1e4c7612a5671bde5/style.css#L79

Can you try and remove all mentions of z-index in your CSS?

hint
use background-url for circles and just position them right, they don't have to exist as a individual
elements.

**Comment by nlukic97** [comment]
Thanks for the feedback. This should fix it:

https://github.com/nlukic97/zadatak_1/blob/921345e1f5491c54164c926490beedf0b0317f76/style.css#L62

(all mentions of Z-index, and the div's for the two circles have been removed).
